### ISSUE TITLE
only matching images ..different images with same face are not recogizing

### ISSUE THREAD

**Issue by ShraddhaGadesha** [kairosinc/Kairos-SDK-Android#3] opened 2016-06-09 14:29 UTC
In my demo I am adding one image of mine using enroll api with subject id "test".
Now I am again choose same image from gallery and call recognize api ,it's giving me proper response.

But I choose second image of mine (i.e faces of both images are same) but now recognize api giving now search found.pls help about this

**Comment by coleca** [comment] 2016-06-09 14:39
Duplicate of issue #2 closing

**Closed as completed by coleca** 2016-06-09 14:39 UTC
